version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.13
    environment:
      POSTGRES_PASSWORD: emir
      POSTGRES_USER: emir
      POSTGRES_DB: simple_messenger
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: