server:
  port: 8080

spring:
  application:
    name: simple-messenger
  datasource:
    password: emir
    username: emir
    url: jdbc:postgresql://localhost:5432/simple_messenger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/postgres
    baseline-on-migrate: true
    schemas: public


